language: generic
sudo: required

services:
  - docker
  
before_install:
  - docker build -t dockenigma/multi-docker -f client/Dockerfile.dev client

script:
  - docker run dockenigma/multi-docker npm run test-coverage

after_success: 
  - docker build -t dockenigma/multi-client ./client
  - docker build -t dockenigma/multi-nginx ./nginx
  - docker build -t dockenigma/multi-server ./server
  - docker build -t dockenigma/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dockenigma/multi-client 
  - docker push dockenigma/multi-nginx
  - docker push dockenigma/multi-server
  - docker push dockenigma/multi-worker





  
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker"
#   env:  "Docker-env"
#   bucket_name: "elasticbeanstalk-us-east-1-444230913747"
#   bucket_path : "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
